# -*- coding: utf-8 -*-
"""stochastic_process_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1BXmOw5EkBLbAKdfxpevx4V8TvXj0C3
"""

# Empirical Study of Stochastic Processes
# Expected Value vs Variance (Simulation)

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

# 1. Bernoulli Process (Convergence to Expected Value)

def bernoulli_process(p=0.55, n_trials=5000):
    outcomes = np.random.rand(n_trials) < p
    outcomes = outcomes.astype(int)
    sample_mean = np.cumsum(outcomes) / np.arange(1, n_trials + 1)
    return sample_mean

sample_mean = bernoulli_process()

plt.figure(figsize=(8, 4))
plt.plot(sample_mean, label="Sample Mean")
plt.axhline(0.55, color="red", linestyle="--", label="Expected Value")
plt.title("Bernoulli Process: Convergence to Expected Value")
plt.xlabel("Number of Trials")
plt.ylabel("Mean Outcome")
plt.legend()
plt.show()

# 2. Random Walk (Expectation = 0, Risk Grows)

def random_walk(n_steps=1000):
    steps = np.random.choice([-1, 1], size=n_steps)
    return np.cumsum(steps)

plt.figure(figsize=(8, 4))
for _ in range(5):
    plt.plot(random_walk(), alpha=0.7)

plt.title("Random Walk Paths (Expectation = 0, Risk Grows)")
plt.xlabel("Steps")
plt.ylabel("Position")
plt.show()

# 3. Equal Expected Value, Different Risk

# Game A: small wins and losses (low variance)
def game_A(n=1000):
    return np.sum(np.random.choice([1, -1], size=n))

# Game B: frequent small wins, rare large loss (high variance)
# Expected value per step:
# 0.95 * 1 + 0.05 * (-19) = 0
def game_B(n=1000):
    outcomes = np.random.rand(n)
    return np.sum(np.where(outcomes < 0.95, 1, -19))

# Run simulations
A_results = [game_A() for _ in range(1000)]
B_results = [game_B() for _ in range(1000)]

# 4. Distribution Comparison

plt.figure(figsize=(8, 4))
plt.hist(A_results, bins=40, alpha=0.6, label="Game A")
plt.hist(B_results, bins=40, alpha=0.6, label="Game B")
plt.title("Equal Expected Value ≠ Equal Risk")
plt.xlabel("Total Outcome")
plt.ylabel("Frequency")
plt.legend()
plt.show()

# 5. Summary Statistics

print("Game A - Mean:", np.mean(A_results), "Std:", np.std(A_results))
print("Game B - Mean:", np.mean(B_results), "Std:", np.std(B_results))